export const MangaActionTypes = {
    SET_ANIMES: "SET_ANIMES",
    SELECTED_ANIME: "SELECTED_ANIME",
    REMOVE_SELECTED_ANIME: "REMOVE_SELECTED_ANIME",
    SELECTED_ANIME_COVER: "SELECTED_ANIME_COVER",
    REMOVE_SELECTED_ANIME_COVER: "REMOVE_SELECTED_ANIME_COVER",
    ANIME_ERRORS: "ANIME_ERRORS",
    NEXT_PAGE: "NEXT_PAGE",
    PREV_PAGE: "PREV_PAGE",
}